// songs actions
export const SET_FAVOURITE_SONGS = 'SET_FAVOURITE_SONGS';
export const RESET_FAVOURITE_SONGS = 'RESET_FAVOURITE_SONGS';
export const SET_SEARCHED_SONGS = 'SET_SEARCHED_SONGS';
export const RESET_SEARCHED_SONGS = 'RESET_SEARCHED_SONGS';
export const SET_TRENDING_SONGS = 'SET_TRENDING_SONGS';
export const RESET_TRENDING_SONGS = 'RESET_TRENDING_SONGS';

//control action
export const SET_CUREENT_LIST = 'SET_CUREENT_LIST';
export const RESET_CUREENT_LIST = 'RESET_CUREENT_LIST';
